<a href="https://colab.research.google.com/github/notGAYathri/Python-codes/blob/main/Python%2310.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Pandas is a python library. ALso called Panel Data,it as created by Wes McKinney in 2008. 
import pandas as pd
from google.colab import files
supermarket=files.upload()


Saving Supermarket_sales.csv to Supermarket_sales.csv


In [7]:
dataframe=pd.read_csv("Supermarket_sales.csv")
print(dataframe)

       No    InvoiceID Branch       City Customertype  Gender  \
0       1  750-67-8428      A     Yangon       Member  Female   
1       2  226-31-3081      C  Naypyitaw       Normal  Female   
2       3  631-41-3108      A     Yangon       Normal    Male   
3       4  123-19-1176      A     Yangon       Member    Male   
4       5  373-73-7910      A     Yangon       Normal    Male   
..    ...          ...    ...        ...          ...     ...   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
0         Health and beauty      74.69         7  26.1415   548.9715   
1    Electronic accessories      15.28         5   3.8200    80.2200   
2  

In [13]:
dataframe=pd.read_csv("Supermarket_sales.csv")
print(dataframe.head())

   No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   
4   5  373-73-7910      A     Yangon       Normal    Male   

              Productline  Unitprice  Quantity      Tax     Total       Date  \
0       Health and beauty      74.69         7  26.1415  548.9715   1/5/2019   
1  Electronic accessories      15.28         5   3.8200   80.2200   3/8/2019   
2      Home and lifestyle      46.33         7  16.2155  340.5255   3/3/2019   
3       Health and beauty      58.22         8  23.2880  489.0480  1/27/2019   
4       Sports and travel      86.31         7  30.2085  634.3785   2/8/2019   

    Time      Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
0  13:08      Ewallet  522.83                 4.761905        26.1415   

In [16]:
#displaying a specific row
dataframe.loc[1]

No                                              2
InvoiceID                             226-31-3081
Branch                                          C
City                                    Naypyitaw
Customertype                               Normal
Gender                                     Female
Productline                Electronic accessories
Unitprice                                   15.28
Quantity                                        5
Tax                                          3.82
Total                                       80.22
Date                                     3/8/2019
Time                                        10:29
Payment                                      Cash
cogs                                         76.4
gross_margin_percentage                  4.761905
gross_iincome                                3.82
Rating                                        9.6
Name: 1, dtype: object

In [18]:
dataframe.loc[4]

No                                         5
InvoiceID                        373-73-7910
Branch                                     A
City                                  Yangon
Customertype                          Normal
Gender                                  Male
Productline                Sports and travel
Unitprice                              86.31
Quantity                                   7
Tax                                  30.2085
Total                               634.3785
Date                                2/8/2019
Time                                   10:37
Payment                              Ewallet
cogs                                  604.17
gross_margin_percentage             4.761905
gross_iincome                        30.2085
Rating                                   5.3
Name: 4, dtype: object

In [21]:
dataframe[["City",'Branch']]

City Branch
0       Yangon      A
1    Naypyitaw      C
2       Yangon      A
3       Yangon      A
4       Yangon      A
..         ...    ...
995  Naypyitaw      C
996   Mandalay      B
997     Yangon      A
998     Yangon      A
999     Yangon      A

[1000 rows x 2 columns]

In [22]:
print(dataframe.index)

RangeIndex(start=0, stop=1000, step=1)


In [23]:
 dataframe=dataframe.drop(['Tax'],axis=1)#axis 0 is for rows and 1 is for columns
 dataframe.head(4)

No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   

              Productline  Unitprice  Quantity     Total       Date   Time  \
0       Health and beauty      74.69         7  548.9715   1/5/2019  13:08   
1  Electronic accessories      15.28         5   80.2200   3/8/2019  10:29   
2      Home and lifestyle      46.33         7  340.5255   3/3/2019  13:23   
3       Health and beauty      58.22         8  489.0480  1/27/2019  20:33   

       Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
0      Ewallet  522.83                 4.761905        26.1415     9.1  
1         Cash   76.40                 4.761905         3.8200     9.6  
2  Credit card  324.31                 4.761905        16.2155     7.4  
3      Ewallet  465.76                 4.761905        23.2880     8.4

In [27]:
 dataframe=dataframe.drop(['gross_margin_percentage'],axis=1)
 dataframe.head(3)

No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   

              Productline  Unitprice  Quantity     Total      Date   Time  \
0       Health and beauty      74.69         7  548.9715  1/5/2019  13:08   
1  Electronic accessories      15.28         5   80.2200  3/8/2019  10:29   
2      Home and lifestyle      46.33         7  340.5255  3/3/2019  13:23   

       Payment    cogs  gross_iincome  Rating  
0      Ewallet  522.83        26.1415     9.1  
1         Cash   76.40         3.8200     9.6  
2  Credit card  324.31        16.2155     7.4

In [33]:
 dataframe=dataframe.drop([1],axis=0)
 dataframe.head()

No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
4   5  373-73-7910      A     Yangon       Normal    Male   
6   7  355-53-5943      A     Yangon       Member  Female   
7   8  315-22-5665      C  Naypyitaw       Normal  Female   

              Productline  Unitprice  Quantity     Total       Date   Time  \
0       Health and beauty      74.69         7  548.9715   1/5/2019  13:08   
2      Home and lifestyle      46.33         7  340.5255   3/3/2019  13:23   
4       Sports and travel      86.31         7  634.3785   2/8/2019  10:37   
6  Electronic accessories      68.84         6  433.6920  2/25/2019  14:36   
7      Home and lifestyle      73.56        10  772.3800  2/24/2019  11:38   

       Payment    cogs  gross_iincome  Rating  
0      Ewallet  522.83        26.1415     9.1  
2  Credit card  324.31        16.2155     7.4  
4      Ewallet  604.17        30.2085     5.3  
6      Ewallet  413.04        20.6520     5.8  
7      Ewallet  735.60        36.7800     8.0

In [36]:
max_Unitprice=dataframe.Unitprice.idxmax()
print(max_Unitprice)

122


In [42]:
max_cogs=dataframe.cogs.idxmax() #index number of the row
print(max_cogs)
max_cogs=dataframe.Unitprice.max()
print(max_cogs)

350
99.96


In [44]:
min_Unitprice=dataframe.Unitprice.idxmin()
print(min_Unitprice)
min_Unitprice=dataframe.Unitprice.min()
print(min_Unitprice)

944
10.08


In [45]:
mean_Unitprice=dataframe.Unitprice.mean()
print(mean_Unitprice)

55.68028084252759


In [46]:
#printing the details of all the ormal customers
dataframe.loc[dataframe['Customertype']=="Normal"]

No    InvoiceID Branch       City Customertype  Gender  \
2      3  631-41-3108      A     Yangon       Normal    Male   
4      5  373-73-7910      A     Yangon       Normal    Male   
7      8  315-22-5665      C  Naypyitaw       Normal  Female   
12    13  365-64-0515      A     Yangon       Normal  Female   
13    14  252-56-2699      A     Yangon       Normal    Male   
..   ...          ...    ...        ...          ...     ...   
992  993  745-74-0715      A     Yangon       Normal    Male   
993  994  690-01-6631      B   Mandalay       Normal    Male   
995  996  233-67-5758      C  Naypyitaw       Normal    Male   
996  997  303-96-2227      B   Mandalay       Normal  Female   
998  999  347-56-2442      A     Yangon       Normal    Male   

                Productline  Unitprice  Quantity      Total       Date   Time  \
2        Home and lifestyle      46.33         7   340.5255   3/3/2019  13:23   
4         Sports and travel      86.31         7   634.3785   2/8/2019  10:37   
7        Home and lifestyle      73.56        10   772.3800  2/24/2019  11:38   
12   Electronic accessories      46.95         5   246.4875  2/12/2019  10:25   
13       Food and beverages      43.19        10   453.4950   2/7/2019  16:48   
..                      ...        ...       ...        ...        ...    ...   
992  Electronic accessories      58.03         2   121.8630  3/10/2019  20:46   
993     Fashion accessories      17.49        10   183.6450  2/22/2019  18:35   
995       Health and beauty      40.35         1    42.3675  1/29/2019  13:46   
996      Home and lifestyle      97.38        10  1022.4900   3/2/2019  17:16   
998      Home and lifestyle      65.82         1    69.1110  2/22/2019  15:33   

         Payment    cogs  gross_iincome  Rating  
2    Credit card  324.31        16.2155     7.4  
4        Ewallet  604.17        30.2085     5.3  
7        Ewallet  735.60        36.7800     8.0  
12       Ewallet  234.75        11.7375     7.1  
13       Ewallet  431.90        21.5950     8.2  
..           ...     ...            ...     ...  
992      Ewallet  116.06         5.8030     8.8  
993      Ewallet  174.90         8.7450     6.6  
995      Ewallet   40.35         2.0175     6.2  
996      Ewallet  973.80        48.6900     4.4  
998         Cash   65.82         3.2910     4.1  

[497 rows x 16 columns]

In [48]:
dataframe.loc[dataframe['Gender']=="Female"]

No    InvoiceID Branch       City Customertype  Gender  \
0       1  750-67-8428      A     Yangon       Member  Female   
6       7  355-53-5943      A     Yangon       Member  Female   
7       8  315-22-5665      C  Naypyitaw       Normal  Female   
8       9  665-32-9167      A     Yangon       Member  Female   
9      10  692-92-5582      B   Mandalay       Member  Female   
..    ...          ...    ...        ...          ...     ...   
990   991  886-18-2897      A     Yangon       Normal  Female   
991   992  602-16-6955      B   Mandalay       Normal  Female   
994   995  652-49-6720      C  Naypyitaw       Member  Female   
996   997  303-96-2227      B   Mandalay       Normal  Female   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Total       Date   Time  \
0         Health and beauty      74.69         7   548.9715   1/5/2019  13:08   
6    Electronic accessories      68.84         6   433.6920  2/25/2019  14:36   
7        Home and lifestyle      73.56        10   772.3800  2/24/2019  11:38   
8         Health and beauty      36.26         2    76.1460  1/10/2019  17:15   
9        Food and beverages      54.84         3   172.7460  2/20/2019  13:27   
..                      ...        ...       ...        ...        ...    ...   
990      Food and beverages      56.56         5   296.9400  3/22/2019  19:06   
991       Sports and travel      76.60        10   804.3000  1/24/2019  18:10   
994  Electronic accessories      60.95         1    63.9975  2/18/2019  11:40   
996      Home and lifestyle      97.38        10  1022.4900   3/2/2019  17:16   
999     Fashion accessories      88.34         7   649.2990  2/18/2019  13:28   

         Payment    cogs  gross_iincome  Rating  
0        Ewallet  522.83        26.1415     9.1  
6        Ewallet  413.04        20.6520     5.8  
7        Ewallet  735.60        36.7800     8.0  
8    Credit card   72.52         3.6260     7.2  
9    Credit card  164.52         8.2260     5.9  
..           ...     ...            ...     ...  
990  Credit card  282.80        14.1400     4.5  
991      Ewallet  766.00        38.3000     6.0  
994      Ewallet   60.95         3.0475     5.9  
996      Ewallet  973.80        48.6900     4.4  
999         Cash  618.38        30.9190     6.6  

[500 rows x 16 columns]

In [49]:
import numpy as np


In [50]:
student_marks_BA=[12,13,14]
marksarray=np.array(student_marks_BA)
print(marksarray)

[12 13 14]


In [51]:
student_marks_BA=[[12,13,14],[10,12,15],[20,30,40]]
marksarray=np.array(student_marks_BA)
print(marksarray)

[[12 13 14]
 [10 12 15]
 [20 30 40]]


In [57]:
markss=[[12,13],[10,12],[20,30],[6,8]]
markarray=np.array(markss)
print(markarray)

[[12 13]
 [10 12]
 [20 30]
 [ 6  8]]


In [58]:
markarray.shape

(4, 2)

In [59]:
values1=np.arange(20)
print(values1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [60]:
values2=np.arange(5,21,2)
print(values2)

[ 5  7  9 11 13 15 17 19]


In [63]:
arayayyy=np.arange(70,101,3)
print(arayayyy)

[ 70  73  76  79  82  85  88  91  94  97 100]


In [65]:
zeroo=np.zeros((2,6)) #row is first,column is second
print(zeroo)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [66]:
zerohero=np.zeros((4,2))
print(zerohero)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [67]:
woohoo=np.ones((8,2))
print(woohoo)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [68]:
identityarray=np.eye(5)
print(identityarray)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [72]:
firstarray=np.array([[10,20,30],[2,4,8],[5,15,20],[2,4,6]])
print(firstarray)


[[10 20 30]
 [ 2  4  8]
 [ 5 15 20]
 [ 2  4  6]]


In [75]:
secondarray=firstarray.reshape(3,4)
print(secondarray)

[[10 20 30  2]
 [ 4  8  5 15]
 [20  2  4  6]]


In [76]:
values=np.random.randint(1,3,5)
print(values)

[2 1 1 1 1]


In [79]:
values1=np.random.randint(7,10,7)
print(values1)

[9 7 7 9 9 8 7]


In [81]:
values=np.random.randint(1,20,(5,3))
print(values)

[[10  1 15]
 [ 3 18  3]
 [ 9 18 19]
 [11 10  3]
 [ 3 14  6]]
